<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
?>
<?php 

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 $request = $objectManager->get('\Magento\Framework\App\Request\Http');
 // $request->getControllerName() . '<br />'; // category
  $FullActionName = $request->getFullActionName(); // catalog_category_view
  if($FullActionName == "catalog_category_view"){
?>
 <div class="cat-ttl">
 	<?php  
      $storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
    $currentStore = $storeManager->getStore();
 	 $mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

   $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');

   	if($category->getImage()){
 	 ?>

 	 <div class="cat-header-sec">
 	 <div class="cat-img"> 
  		<img src="<?php echo $mediaUrl.'/catalog/category/'.$category->getImage();  ?>" style=" width:100%; height:150px;" >
  	 </div>
  	 <?php if ($title){ ?>
	  	<span class="page-header h1 cat-title">
			<?php /* @escapeNotVerified */ echo $title ?>
		</span>
	<?php } ?>
	</div>
  	<?php }else{ ?>
  		<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php 
	$image = "";
	if($themeHelper->getStoreConfig('mpanel/breadcrumbs/bg_title_page')) {
		$ObjectManagerMap = \Magento\Framework\App\ObjectManager::getInstance();
		$storeManager = $ObjectManagerMap->get('Magento\Store\Model\StoreManagerInterface');
		$currentStore = $storeManager->getStore();
		$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
		$image = $mediaUrl.'bg_page_title/'.$themeHelper->getStoreConfig('mpanel/breadcrumbs/bg_title_page');
	}
?>
	<div class="page-title-wrapper<?php /* @escapeNotVerified */ echo $cssClass; ?>" <?php if($image != ""): ?>style="background-image: url('<?php echo $image; ?>');"<?php endif ?>>
			<?php if ($title){ ?>
	  	<span class="page-header h1"
			<?php if ($block->getId()): ?> id="<?php /* @escapeNotVerified */ echo $block->getId();?>" <?php endif; ?>
			<?php if ($block->getAddBaseAttributeAria()): ?>
				aria-labelledby="<?php /* @escapeNotVerified */ echo $block->getAddBaseAttributeAria(); ?>"
			<?php endif; ?>>
			<?php /* @escapeNotVerified */ echo $title ?>
		</span>
		<?php } ?>
	</div>
  	<?php } ?>
  
 </div> 
<?php }else{ ?>
<?php if ($title): ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php 
	$image = "";
	if($themeHelper->getStoreConfig('mpanel/breadcrumbs/bg_title_page')) {
		$ObjectManagerMap = \Magento\Framework\App\ObjectManager::getInstance();
		$storeManager = $ObjectManagerMap->get('Magento\Store\Model\StoreManagerInterface');
		$currentStore = $storeManager->getStore();
		$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
		$image = $mediaUrl.'bg_page_title/'.$themeHelper->getStoreConfig('mpanel/breadcrumbs/bg_title_page');
	}
?>
<div class="page-title-wrapper<?php /* @escapeNotVerified */ echo $cssClass; ?>" <?php if($image != ""): ?>style="background-image: url('<?php echo $image; ?>');"<?php endif ?>>
	<div class="container">
		<?php if($themeHelper->getStoreConfig('mpanel/product_details/show_product_name')): ?>
			<span class="page-header h1"
				<?php if ($block->getId()): ?> id="<?php /* @escapeNotVerified */ echo $block->getId();?>" <?php endif; ?>
				<?php if ($block->getAddBaseAttributeAria()): ?>
					aria-labelledby="<?php /* @escapeNotVerified */ echo $block->getAddBaseAttributeAria(); ?>"
				<?php endif; ?>>
				<?php /* @escapeNotVerified */ echo $title ?>
			</span>
		<?php else: ?>
			<h1 class="page-header"
				<?php if ($block->getId()): ?> id="<?php /* @escapeNotVerified */ echo $block->getId();?>" <?php endif; ?>
				<?php if ($block->getAddBaseAttributeAria()): ?>
					aria-labelledby="<?php /* @escapeNotVerified */ echo $block->getAddBaseAttributeAria(); ?>"
				<?php endif; ?>>
				<?php /* @escapeNotVerified */ echo $title ?>
			</h1>
		<?php endif; ?>
		<?php echo $block->getChildHtml(); ?>
	</div>
</div>
<?php endif; ?>
<?php } ?>