<table autosize="2" class="medium-main-1c-side-2c-bottom gallery single-image-medium">
    <tr>
        <td class="centerimage main-image-medium-2col col-sm-9" style="border: 0px;border-spacing: 0px;">
            <img class="img-responsive" src="<?php echo $this->getMainImageUrl(); ?>" />
        </td>
        <td class="col-sm-3">
            <table class="gallery col1-right-gallery">
                <?php
                foreach($this->getMediaGalleryImagesSelection(1,3) as $image){ ?>
                    <tr>
                        <td class="centerimage" style="max-width:200px;">
                            <img style="max-width:200px" class="img-responsive" src="<?php echo $image->getUrl(); ?>" />
                        </td>
                    </tr>
                <?php } ?>
            </table>
        </td>
    </tr>
</table>
<?php /* ?>
<table class="gallery medium-main-1c-side-2c-bottom bottom-gallery">
    <?php
    $i = 0;
    foreach($this->getMediaGalleryImagesSelection(4, 100) as $image){ ?>
        <?php if($i % 1 == 0){ ?>
            <tr>
        <?php } ?>
        <td class="centerimage col-sm-6" style="border: 0px;border-spacing: 0px;">
            <img class="img-responsive" src="<?php echo $image->getUrl(); ?>" />
        </td>
        <?php if($i % 1 == 0 || $i == ($this->getSelectionImageCount(4, 100) - 1)){ ?>
            </tr>
        <?php }
        $i++;
    } ?>
</table>
<?php */ ?>