<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Feed
 */
?>
<?php
/** @var \Amasty\Feed\Block\Adminhtml\Category\Edit\Tab\Mapping $block */
$_value = $block->getElement()->getValue();
$_htmlId = $block->getElement()->getHtmlId();
$_htmlClass = $block->getElement()->getClass();
$_htmlName = $block->getElement()->getName();
$_readonly = $block->getElement()->getReadonly()
?>
<div class="field" id="attribute-<?= $_htmlId?>-container">
    <label class="label"><span><?= $block->getElement()->getLabel(); ?></span></label>
    <div class="control">
        <ul style="list-style-type: none;">
            <?php foreach($this->getCategoriesList() as $category): ?>
                <li style="padding:3px 0 3px <?= ($category['level'] * 30) ?>px;">
                    <input
                            type="checkbox"
                            title="<?= __('Ignore category') ?>"
                            name="mapping[<?= $category['id'] ?>][skip]"
                            value="1"
                            <?php if (isset($_value[$category['id']]['skip']) && $_value[$category['id']]['skip']): ?>
                            checked="checked"
                            <?php endif; ?>
                    />
                    <?php if (isset($_value[$category['id']]) && ($variable = $_value[$category['id']]['name'])): ?>
                         <span>
                             <a href="#" onclick="mappingControl.modify(<?= $category['id']?>, '<?= $block->escapeHtml($block->escapeJsQuote($variable))?>', '<?= $block->escapeHtml($block->escapeJsQuote($category['name']))?>', this); return false;"><?= $block->escapeHtml($variable);?></a>
                         </span>
                         <span>&nbsp;(<?= $block->escapeHtml($category['name'])?>)</span>
                     <?php else: ?>
                         <span>
                         <a href="#" onclick="mappingControl.modify(<?= $category['id']?>, '', '<?= $block->escapeHtml($block->escapeJsQuote($category['name']))?>', this); return false;"><?= $block->escapeHtml($category['name']);?></a>
                         </span>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>

<script>
    require([
        'mage/template',
        "prototype",
        "mage/adminhtml/form"
    ], function (mageTemplate) {
        //<![CDATA[
        var fieldRowTemplate = '<input class="input-text" type="text" '
            + 'name="<?= $_htmlName; ?>[<%- data.id %>][name]" '
            + 'value="<%- data.value %>" '
            + 'placeholder="<%- data.placeholder %>"'
            + '/>';

        var mappingControl = {
            template: mageTemplate(fieldRowTemplate),
            modify: function (id, value, placeholder, link) {
                var data = {
                    id: id,
                    value: value,
                    placeholder: placeholder
                };

                $(link).hide();

                Element.insert($(link).up('span'), {
                    bottom: this.template({
                        data: data
                    })
                });
            }
        };

        window.mappingControl = mappingControl;
        //]]>
    });
</script>
